
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: 

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^LICENSE
  - server/
  - files/